# Default values for frontend-registration-payments.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 451298871710.dkr.ecr.us-east-1.amazonaws.com/prod/frontend-payments-registration
  tag: latest
  pullPolicy: Always

nginx:
  hosts:
    - www.foldingtogether.net
    - www.foldtogether.org
    - foldtogether.org
  image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent

application:
  env:
    aws_sqs_donation_queue: https://queue.amazonaws.com/451298871710/folding-together-compute-BankerStack-CXLLGMSUKZ4G-Queue-3ZY5MGTZ4BTK

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
  hosts:
    - host: www.foldingtogether.net
      paths:
        - /
    - host: foldtogether.org
      paths:
        - /
    - host: www.foldtogether.org
      paths:
        - /

postgresql:
  existingSecret: frontend-registration-postgres-creds
  postgresqlUsername: service_user
  postgresqlDatabase: service_db

resources:
 limits:
   cpu: 200m
   memory: 256Mi
 requests:
   cpu: 100m
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
