# Generated by Django 3.0.4 on 2020-03-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='charged_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
