# Generated by Django 3.0.4 on 2020-03-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_donation_charged_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='new_donation_event_dispatch_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
