# Generated by Django 3.0.4 on 2020-03-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
