
---
AWSTemplateFormatVersion: 2010-09-09
Description: Bank balance tracking resources
Resources:
  Queue:
    Type: AWS::SQS::Queue
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W48 ## skip for MVP
            reason: Queue encryption skipped for MVP

  DonationProcessorRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: CloudWatch actions do not support resource-level permissions.
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub lambda.${AWS::URLSuffix}
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GetBalance
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: cloudwatch:GetMetricData
                Resource: '*'
        - PolicyName: PutBalance
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: cloudwatch:PutMetricData
                Resource: '*'
                Condition:
                  StringEquals:
                    cloudwatch:namespace: FT-Bank
        - PolicyName: QueueProcessing
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                Resource: !GetAtt Queue.Arn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  DonationProcessor:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: folding-together-artifacts
        S3Key: lambda/donation_processor.zip
      Environment:
        Variables:
          QueueUrl: !Ref Queue
      Handler: donation_processor.lambda_handler
      Role: !GetAtt DonationProcessorRole.Arn
      Runtime: python3.8