
---
AWSTemplateFormatVersion: 2010-09-09
Description: Bank balance tracking resources
Resources:
  Queue:
    Type: AWS::SQS::Queue

  DonationProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub lambda.${AWS::URLSuffix}
            Action: sts:AssumeRole
      Policies:
        - PolicyName: QueueProcessing
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssq:ReceiveMessage
                Resource: !GetAtt Queue.Arn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  DonationProcessor:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: folding-together-artifacts
        S3Key: lambda/donation_processor.zip
      Environment:
        Variables:
          QueueURL: !Ref Queue
      Handler: donation_processor.lambda_handler
      Role: !GetAtt DonationProcessorRole.Arn
      Runtime: python3.8