---
AWSTemplateFormatVersion: 2010-09-09
Description: Main template
Resources:
  BankerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://folding-together-artifacts.s3.amazonaws.com/cloudformation/donation_processor.yaml

  # ComputeStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     # https://github.com/jkataja/cfn-foldingathome/blob/master/foldingathome.yml
  #     TemplateURL: https://folding-together-artifacts.s3.amazonaws.com/cloudformation/compute.yaml