---
AWSTemplateFormatVersion: 2010-09-09
Description: Main template
Resources:
  BankerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://folding-together-artifacts.s3.amazonaws.com/cloudformation/banker.yaml
