
---
AWSTemplateFormatVersion: 2010-09-09
Description: Compute scheduling resources
Parameters:
  TableArn:
    Description: ARN of the DynamoDB table for storing balances
    Type: String
  TableName:
    Description: Name of the DynamoDB table for storing balances
    Type: String
Resources:
  LookupFundingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub lambda.${AWS::URLSuffix}
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LookupBalance
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: dynamodb:Scan
                Resource: !Ref TableArn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LookingFunding:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: folding-together-artifacts
        S3Key: lambda/lookup_funding.zip
      Environment:
        Variables:
          TableName: !Ref TableName
      Handler: lookup_funding.lambda_handler
      Role: !GetAtt LookupFundingRole.Arn
      Runtime: python3.8

  LookupInstanceCostRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: DescribeSpotInstanceRequests does not support resource-level permissions.
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub lambda.${AWS::URLSuffix}
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GetInstancePrices
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ec2:DescribeSpotInstanceRequests
                Resource: '*'
        - PolicyName: LookupResources
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: cloudformation:DescribeStackResource
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LookupInstanceCost:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: folding-together-artifacts
        S3Key: lambda/lookup_instance_cost.zip
      Handler: lookup_instance_cost.lambda_handler
      Role: !GetAtt LookupInstanceCostRole.Arn
      Runtime: python3.8

  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub states.${AWS::Region}.${AWS::URLSuffix}
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole

  ComputeSchedulerStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString: !Sub |-
        {
          "Comment": "Folding Together compute scheduling",
          "StartAt": "LookupFunding",
          "States": {
            "LookupFunding": {
              "Type": "Task",
              "Resource": "${LookingFunding.Arn}",
              "Next": "FundedLoop"
            },
            "FundedLoop": {
              "Type": "Map",
              "ItemsPath": "$.Items",
              "Iterator": {
                "StartAt": "LookupInstanceCost",
                "States": {
                  "LookupInstanceCost": {
                    "Type": "Task",
                    "Resource": "${LookupInstanceCost.Arn}",
                    "End": true
                  }
                }
              },
              "End": true
            }
          }
        }
      RoleArn: !GetAtt StepFunctionRole.Arn
