apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-registration-payments.fullname" . }}
  labels:
{{ include "frontend-registration-payments.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "frontend-registration-payments.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/sites-enabled-configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "frontend-registration-payments.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: sites-enabled
          configMap:
            name: {{ include "frontend-registration-payments.fullname" . }}-sites-enabled-configmap
        - name: staticfiles
          emptyDir: {}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "manage.py", "migrate"]
          env:
{{ include "frontend-registration-payments.env" . | indent 12 }}
        - name: {{ .Chart.Name }}-collectstatic
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          volumeMounts:
            - name: staticfiles
              mountPath: /var/www/html/static
          env:
{{ include "frontend-registration-payments.env" . | indent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["gunicorn", "gateway.wsgi"]
          ports:
            - name: wsgi
              containerPort: 8000
              protocol: TCP
          env:
{{ include "frontend-registration-payments.env" . | indent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          volumeMounts:
            - name: sites-enabled
              mountPath: /etc/nginx/conf.d/
            - name: staticfiles
              mountPath: /var/www/html/static
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ht
              port: http
          readinessProbe:
            httpGet:
              path: /ht
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
