version: '3'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./gateway:/code
    ports:
      - "8000:8000"
    environment:
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_NAME: postgres
    depends_on:
      - db
